language: generic 
sudo: required 
services: 
    - docker
    
before_install:
    - docker build -t shlomi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shlomi/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-996882743245"
    bucket_path: "docker-react-app"
    on:
        branch: master
    access_key_id: $AWS_ID
    secret_access_key: $AWS_SECRET