sudo: required 
services: 
    - docker
    
before_install:
    - docker build -t shlomi/docker-react -f Dockerfile.dev .

script:
    - docker run shlomi/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-996882743245"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "AKIA6QGWXP7GSI5JHJPQ"
    secret_access_key: "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"